/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        slate: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          850: '#151F32',
          900: '#0F172A',
          950: '#020617',
        },
        primary: {
          DEFAULT: 'var(--color-primary)',
          hover: 'var(--color-primary-hover)',
          light: 'var(--color-primary-light)',
          dark: 'var(--color-primary-dark)',
          subtle: 'var(--color-primary-subtle)',
        },
        lp: {
          heading: 'var(--lp-heading)',
          body: 'var(--lp-body)',
          'body-muted': 'var(--lp-body-muted)',
          secondary: 'var(--lp-secondary)',
          'secondary-dim': 'var(--lp-secondary-dim)',
          muted: 'var(--lp-muted)',
          subtle: 'var(--lp-subtle)',
          'subtle-static': 'var(--lp-subtle-static)',
          white: 'var(--lp-white)',
          green: 'var(--lp-green)',
          star: 'var(--lp-star)',
          'amber-text': 'var(--lp-amber-demotext)',
          'amber-label': 'var(--lp-amber-label)',
          page: 'var(--lp-bg-page)',
          card: 'var(--lp-bg-card)',
          elevated: 'var(--lp-bg-elevated)',
          'elevated-hover': 'var(--lp-bg-elevated-hover)',
          'elevated-dim': 'var(--lp-bg-elevated-dim)',
          avatar: 'var(--lp-bg-avatar)',
          'section-50': 'var(--lp-bg-section-50)',
          'section-80': 'var(--lp-bg-section-80)',
          overlay: 'var(--lp-bg-overlay)',
          header: 'var(--lp-bg-header)',
          'header-border': 'var(--lp-bg-header-border)',
          'hover-light': 'var(--lp-bg-hover-light)',
          'border': 'var(--lp-border)',
          'border-strong': 'var(--lp-border-strong)',
          'border-avatar': 'var(--lp-border-avatar)',
          'border-section': 'var(--lp-border-section)',
          'border-amber': 'var(--lp-border-amber)',
          'border-amber-solid': 'var(--lp-border-amber-solid)',
          'icon-green': 'var(--lp-icon-green)',
          'icon-amber': 'var(--lp-icon-amber)',
          'icon-amber-hover': 'var(--lp-icon-amber-hover)',
          'icon-blue': 'var(--lp-icon-blue)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
